### ISSUE TITLE
duplicate code in shapes3d.py

### ISSUE THREAD

**Issue by vert-rouge** [jeff-dh/SolidPython#25]
Hi,

There is some duplicated code in solid2/extensions/bosl2/shapes3d.py. For example :
`class cube(_Bosl2Base)`

does it helps if I propose a patch with a deduplicated version?

**Comment by jeff-dh** [comment]
Well, the reason is, that there are duplicates in bosl2 unless we
ignore the functions. Don't know whether that would make sense.

https://github.com/revarbat/BOSL2/blob/bfa5fbc81aa2cbdc177e839f68baa62d1ae09b57/shapes3d.scad#L58
https://github.com/revarbat/BOSL2/blob/bfa5fbc81aa2cbdc177e839f68baa62d1ae09b57/shapes3d.scad#L68

Does it cause any issues for you?

**Comment by jeff-dh** [comment]
This is related to #24.

**Comment by vert-rouge** [comment]
thanks for your answer.

Is the code generated from BOSL2 scad code?

I’m not familiar with SCAD language. what does happen when something is define twice?

**Comment by vert-rouge** [comment]
>  Does it cause any issues for you?

I read python code to understand how I should make calls to Bosl2 functions. It makes things a bit more difficult to read. nothing more.

**Comment by jeff-dh** [comment]
Ok, I would suggest to use the bosl2 docs instead, that works pretty good for me:
https://github.com/revarbat/BOSL2/wiki

in particular:
https://github.com/revarbat/BOSL2/wiki/shapes3d.scad#functionmodule-cube

As long as it does not cause any issues I tend to ignore it.

**Comment by vert-rouge** [comment]
let’s do that.
